name: Create pre-release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        required: true

jobs:
  create-release:
    if: github.actor_id != 210085057
    runs-on: ubuntu-latest
    steps:
      - name: Install zip
        run: sudo apt install zip

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest


      - name: Generate GitHub App token
        id: app_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}
          token: ${{ steps.app_token.outputs.token }}


      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run build script
        run: bun run build
        env:
          TGT_RELEASE_VERSION: ${{ github.event.inputs.tag }}


      - name: Push version bump change
        uses: EndBug/add-and-commit@v9
        with:
          add: package.json
          push: true
          default_author: github_actions
          message: 'chore: bump version to ${{ github.event.inputs.tag }}'


      - name: Bundle files
        run: |
          mkdir -p ./temp/oxmysql/{web,lib}
          cp ./{LICENSE,README.md,fxmanifest.lua,ui.lua} ./temp/oxmysql
          cp ./lib/MySQL.lua ./temp/oxmysql/lib
          cp -r ./dist ./logger ./temp/oxmysql
          cp -r ./web/build ./temp/oxmysql/web/
          cd ./temp && zip -r ../oxmysql.zip ./oxmysql

      - name: Create release
        uses: 'marvinpinto/action-automatic-releases@v1.2.1'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          automatic_release_tag: ${{ github.event.inputs.tag }}
          files: oxmysql.zip
